//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateStatistics
    {
        public DateStatistics()
        {
            this.User = new HashSet<User>();
        }
    
        public int DateStatID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
