//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBook
    {
        public EBook()
        {
            this.Chapter = new HashSet<Chapter>();
            this.User = new HashSet<User>();
            this.Favorite = new HashSet<Favorite>();
        }
    
        public int EbookID { get; set; }
        public string EBookName { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Subject { get; set; }
    
        public virtual ICollection<Chapter> Chapter { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Favorite> Favorite { get; set; }
    }
}
