//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBookStatistics
    {
        public int EBookStatID { get; set; }
        public int NumTimesRead { get; set; }
        public int ChapterID { get; set; }
        public int UserID { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual User User { get; set; }
    }
}
