//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> UserSet { get; set; }
        public DbSet<EBook> EBookSet { get; set; }
        public DbSet<Chapter> ChapterSet { get; set; }
        public DbSet<Bookmark> BookmarkSet { get; set; }
        public DbSet<Favorite> FavoriteSet { get; set; }
        public DbSet<ConsultedEbooks> ConsultedEbooksSet { get; set; }
        public DbSet<DateStatistics> DateStatisticsSet { get; set; }
    }
}
